# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitterWindow = QtWidgets.QSplitter(self.centralwidget)
        self.splitterWindow.setGeometry(QtCore.QRect(20, 20, 1251, 281))
        self.splitterWindow.setOrientation(QtCore.Qt.Horizontal)
        self.splitterWindow.setObjectName("splitterWindow")
        self.splitter_Video = QtWidgets.QSplitter(self.splitterWindow)
        self.splitter_Video.setOrientation(QtCore.Qt.Vertical)
        self.splitter_Video.setObjectName("splitter_Video")
        self.frameVideoPlayer = QtWidgets.QFrame(self.splitter_Video)
        self.frameVideoPlayer.setFrameShape(QtWidgets.QFrame.Box)
        self.frameVideoPlayer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVideoPlayer.setObjectName("frameVideoPlayer")
        self.frameControlBar = QtWidgets.QFrame(self.splitter_Video)
        self.frameControlBar.setFrameShape(QtWidgets.QFrame.Box)
        self.frameControlBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameControlBar.setObjectName("frameControlBar")
        self.splitterAnnotation = QtWidgets.QSplitter(self.splitterWindow)
        self.splitterAnnotation.setOrientation(QtCore.Qt.Vertical)
        self.splitterAnnotation.setObjectName("splitterAnnotation")
        self.frameAnnotations = QtWidgets.QFrame(self.splitterAnnotation)
        self.frameAnnotations.setFrameShape(QtWidgets.QFrame.Box)
        self.frameAnnotations.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAnnotations.setObjectName("frameAnnotations")
        self.frameAnnotationProperties = QtWidgets.QFrame(self.splitterAnnotation)
        self.frameAnnotationProperties.setFrameShape(QtWidgets.QFrame.Box)
        self.frameAnnotationProperties.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAnnotationProperties.setObjectName("frameAnnotationProperties")
        self.frameAnnotationList = QtWidgets.QFrame(self.splitterAnnotation)
        self.frameAnnotationList.setFrameShape(QtWidgets.QFrame.Box)
        self.frameAnnotationList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAnnotationList.setObjectName("frameAnnotationList")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitterWindow)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Video = QtWidgets.QAction(MainWindow)
        self.actionOpen_Video.setObjectName("actionOpen_Video")
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen_Video)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Video.setText(_translate("MainWindow", "Open Video"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionOpen_Project.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionClose.setText(_translate("MainWindow", "Close Project"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
